package com.group4.model;

import com.group4.lib.data.SimpleFileORM; // Import the ORM annotations
import com.group4.lib.enums.UserRole; // Import the UserRole enum

// Annotate the class as a persistent Entity
@SimpleFileORM.Entity(name = "users") // Optional: specify a custom file name (will create users.txt)
public class UserModel {

    // Annotate the primary key field - Should typically be declared first
    @SimpleFileORM.Id(autoGenerated = true) // Configure ID to be auto-generated by the ORM
    public Long id; // Using Long to match the ORM's ID generation

    // --- Declare fields in the order they appear in the user.txt header (after ID)
    // ---
    @SimpleFileORM.Column(name = "password")
    private String password;

    @SimpleFileORM.Column(name = "role")
    private UserRole role;

    @SimpleFileORM.Column(name = "username")
    private String username;

    @SimpleFileORM.Column(name = "email")
    private String email;

    @SimpleFileORM.Column(name = "firstname")
    private String firstname;

    @SimpleFileORM.Column(name = "lastname")
    private String lastname;

    @SimpleFileORM.Column(name = "photo")
    private String photo;

    @SimpleFileORM.Column(name = "phoneNumber")
    private String phoneNumber;

    @SimpleFileORM.Column(name = "address")
    private String address;
    // -----------------------------------------------------------------------------

    // SimpleFileORM requires a public no-argument constructor for deserialization
    // This constructor MUST remain for the ORM to work correctly.
    public UserModel() {
        // Set the default role to Customer in the no-arg constructor
        // This ensures deserialized users without a role value (from older files) get a
        // default
        this.role = UserRole.Customer;
    }

    // --- Single constructor for creating new User objects ---
    // This constructor includes all fields except the auto-generated ID.
    // The order of parameters here can be flexible, but internally fields are set
    // by name.
    public UserModel(String username, String email, String password, UserRole role) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role; // Assign the specified role
    }

    public UserModel(String username, String email, String password, UserRole role, String firstname, String lastname,
            String photo, String phoneNumber, String address) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
        this.firstname = firstname;
        this.lastname = lastname;
        this.photo = photo;
        this.phoneNumber = phoneNumber;
        this.address = address;
    }

    // ------------------------------------------------------

    // Getters and Setters for all fields (required by SimpleFileORM for reflection)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    // Getter for the email field
    public String getEmail() {
        return email;
    }

    // Setter for the email field
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    // --- Getters and Setters for the role field ---
    public UserRole getRole() {
        return role;
    }

    public void setRole(UserRole role) {
        this.role = role;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
    // ----------------------------------------------

    // Optional: Override toString() for easier debugging and logging
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", role=" + role + // Include role in toString
                ", password='" + password + '\'' + // Be cautious printing passwords in production logs
                '}';
    }
}
