package com.group4.model;

import com.group4.lib.data.SimpleFileORM; // Import the ORM annotations
import com.group4.lib.enums.UserRole; // Import the UserRole enum

// Annotate the class as a persistent Entity
@SimpleFileORM.Entity(name = "users")
public class User {

    @SimpleFileORM.Id(autoGenerated = true)
    private Long id;

    @SimpleFileORM.Column(name = "username")
    private String username;

    @SimpleFileORM.Column(name = "email")
    private String email;

    @SimpleFileORM.Column(name = "password")
    private String password;

    @SimpleFileORM.Column(name = "role")
    private UserRole role;

    // SimpleFileORM requires a public no-argument constructor for deserialization
    public User() {
        this.role = UserRole.Customer;
    }

    // Constructor for creating new User objects (without ID for auto-generation)

    // Optional: Add a constructor to specify the role explicitly
    public User(String username, String email, String password, UserRole role) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    // Getters and Setters for all fields (required by SimpleFileORM for reflection)
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserRole getRole() {
        return role;
    }

    public void setRole(UserRole role) {
        this.role = role;
    }

    // Override toString() for easier debugging and logging
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", role=" + role + // Include role in toString
                ", password='" + password + '\'' + // Be cautious printing passwords in production logs
                '}';
    }
}
