package com.group4.lib.data;

import java.io.*;
import java.lang.annotation.*;
import java.lang.reflect.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.locks.ReentrantLock;

/**
 * SimpleFileORM - A lightweight object-relational mapping system for text file
 * storage.
 * Provides basic CRUD operations with transaction support and type safety.
 *
 * @param <T> The entity type this ORM will manage
 */
public class SimpleFileORM<T> {
    private final Path filePath;
    private final ReentrantLock lock = new ReentrantLock();
    private final Class<T> entityClass;
    private final EntityMetadata metadata;
    private long nextId = 1;

    /**
     * Marks a class as a persistent entity
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    public @interface Entity {
        /**
         * @return Optional custom name for the entity storage file
         */
        String name() default "";
    }

    /**
     * Marks a field as the entity's primary key
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface Id {
        /**
         * @return true if the ID should be auto-generated
         */
        boolean autoGenerated() default true;
    }

    /**
     * Marks a field for persistence in the text file
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface Column {
        /**
         * @return Optional custom column name
         */
        String name() default "";
    }

    private static class EntityMetadata {
        String idField;
        boolean autoGenerateId;
        List<String> fields = new ArrayList<>();
        Map<String, String> columnMappings = new HashMap<>();
    }

    /**
     * Creates a new ORM instance for the specified entity class
     * 
     * @param entityClass The entity class to manage
     * @param filePath    The storage file path
     * @throws ORMException If entity class is invalid or file initialization fails
     */
    public SimpleFileORM(Class<T> entityClass, String filePath) {
        this.entityClass = Objects.requireNonNull(entityClass, "Entity class cannot be null");
        this.filePath = Paths.get(filePath).toAbsolutePath();
        this.metadata = parseEntityMetadata();
        initializeStorage();
        loadNextId();
    }

    private EntityMetadata parseEntityMetadata() {
        validateEntityClass();
        EntityMetadata meta = new EntityMetadata();

        // Process entity-level annotation
        if (entityClass.isAnnotationPresent(Entity.class)) {
            Entity entityAnn = entityClass.getAnnotation(Entity.class);
            // Use annotation name if provided
            if (!entityAnn.name().isEmpty()) {
                // Could use this for file naming or schema validation
            }
        }

        // Process fields
        for (Field field : entityClass.getDeclaredFields()) {
            if (field.isAnnotationPresent(Id.class)) {
                meta.idField = field.getName();
                meta.autoGenerateId = field.getAnnotation(Id.class).autoGenerated();
            }
            if (field.isAnnotationPresent(Column.class)) {
                Column column = field.getAnnotation(Column.class);
                String columnName = column.name().isEmpty() ? field.getName() : column.name();
                meta.columnMappings.put(field.getName(), columnName);
                meta.fields.add(field.getName());
            }
        }

        if (meta.idField == null) {
            throw new ORMException("Entity class must have a field annotated with @Id");
        }

        return meta;
    }

    private void validateEntityClass() {
        if (!entityClass.isAnnotationPresent(Entity.class)) {
            throw new ORMException("Entity class must be annotated with @Entity");
        }

        try {
            entityClass.getDeclaredConstructor();
        } catch (NoSuchMethodException e) {
            throw new ORMException("Entity class must have a public no-arg constructor", e);
        }
    }

    private void initializeStorage() {
        lock.lock();
        try {
            if (!Files.exists(filePath)) {
                Files.createDirectories(filePath.getParent());
                Files.createFile(filePath);
                writeHeader();
            }
        } catch (IOException e) {
            throw new ORMException("Storage initialization failed", e);
        } finally {
            lock.unlock();
        }
    }

    private void writeHeader() throws IOException {
        List<String> header = new ArrayList<>();
        if (metadata.autoGenerateId) {
            header.add("id");
        }
        header.addAll(metadata.columnMappings.values());
        Files.write(filePath, Collections.singleton(String.join(",", header)),
                StandardCharsets.UTF_8);
    }

    /**
     * Persists a new entity to storage
     * 
     * @param entity The entity to persist
     * @return The persisted entity with generated ID (if applicable)
     * @throws ORMException If persistence fails
     */
    public T create(T entity) {
        validateEntity(entity);
        lock.lock();
        try {
            if (metadata.autoGenerateId) {
                entity = generateId(entity);
            }
            String record = serializeEntity(entity);
            appendToFile(record);
            return entity;
        } finally {
            lock.unlock();
        }
    }

    /**
     * Retrieves all entities matching the predicate
     * 
     * @param predicate The filter condition
     * @return List of matching entities (empty if none found)
     * @throws ORMException If query fails
     */
    public List<T> find(Predicate<T> predicate) {
        lock.lock();
        try {
            List<T> results = new ArrayList<>();
            for (String line : Files.readAllLines(filePath)) {
                if (line.startsWith("id,"))
                    continue;
                T entity = deserializeEntity(line);
                if (predicate.test(entity)) {
                    results.add(entity);
                }
            }
            return Collections.unmodifiableList(results);
        } catch (IOException e) {
            throw new ORMException("Query failed", e);
        } finally {
            lock.unlock();
        }
    }

    /**
     * Updates entities matching the predicate
     * 
     * @param predicate Filter condition
     * @param updater   Update function
     * @return Number of updated entities
     * @throws ORMException If update fails
     */
    public int update(Predicate<T> predicate, Function<T, T> updater) {
        lock.lock();
        try {
            List<String> lines = Files.readAllLines(filePath);
            List<String> newLines = new ArrayList<>();
            int updates = 0;

            for (String line : lines) {
                if (line.startsWith("id,")) {
                    newLines.add(line);
                    continue;
                }

                T entity = deserializeEntity(line);
                if (predicate.test(entity)) {
                    T updated = updater.apply(entity);
                    validateEntity(updated);
                    newLines.add(serializeEntity(updated));
                    updates++;
                } else {
                    newLines.add(line);
                }
            }

            if (updates > 0) {
                writeAtomic(newLines);
            }
            return updates;
        } catch (IOException e) {
            throw new ORMException("Update failed", e);
        } finally {
            lock.unlock();
        }
    }

    /**
     * Deletes entities matching the predicate
     * 
     * @param predicate Filter condition
     * @return Number of deleted entities
     * @throws ORMException If deletion fails
     */
    public int delete(Predicate<T> predicate) {
        return update(predicate, entity -> null);
    }

    // Serialization methods
    private String serializeEntity(T entity) {
        List<String> values = new ArrayList<>();
        try {
            if (metadata.autoGenerateId) {
                Field idField = entityClass.getDeclaredField(metadata.idField);
                idField.setAccessible(true);
                values.add(idField.get(entity).toString());
            }

            for (String fieldName : metadata.fields) {
                Field field = entityClass.getDeclaredField(fieldName);
                field.setAccessible(true);
                values.add(field.get(entity).toString());
            }
        } catch (Exception e) {
            throw new ORMException("Serialization failed", e);
        }
        return String.join(",", values);
    }

    private T deserializeEntity(String line) {
        try {
            T entity = entityClass.getDeclaredConstructor().newInstance();
            String[] parts = line.split(",");
            int index = 0;

            if (metadata.autoGenerateId) {
                Field idField = entityClass.getDeclaredField(metadata.idField);
                idField.setAccessible(true);
                idField.set(entity, parseValue(parts[index++], idField.getType()));
            }

            for (String fieldName : metadata.fields) {
                Field field = entityClass.getDeclaredField(fieldName);
                field.setAccessible(true);
                field.set(entity, parseValue(parts[index++], field.getType()));
            }

            return entity;
        } catch (NoSuchMethodException e) {
            throw new ORMException("Missing no-arg constructor in " + entityClass.getName(), e);
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException e) {
            throw new ORMException("Failed to instantiate entity", e);
        } catch (Exception e) {
            throw new ORMException("Deserialization failed", e);
        }
    }

    private Object parseValue(String value, Class<?> type) {
        try {
            if (type == String.class)
                return value;
            if (type == Integer.class || type == int.class)
                return Integer.parseInt(value);
            if (type == Long.class || type == long.class)
                return Long.parseLong(value);
            if (type == Double.class || type == double.class)
                return Double.parseDouble(value);
            if (type == Boolean.class || type == boolean.class)
                return Boolean.parseBoolean(value);
            throw new ORMException("Unsupported type: " + type.getName());
        } catch (NumberFormatException e) {
            throw new ORMException("Invalid value format for type " + type.getName(), e);
        }
    }

    // Helper methods
    private void validateEntity(T entity) {
        try {
            for (String fieldName : metadata.fields) {
                Field field = entityClass.getDeclaredField(fieldName);
                field.setAccessible(true);
                if (field.get(entity) == null && field.getAnnotation(Column.class) != null) {
                    throw new ORMException("Non-nullable field " + fieldName + " cannot be null");
                }
            }
        } catch (Exception e) {
            throw new ORMException("Entity validation failed", e);
        }
    }

    private T generateId(T entity) {
        try {
            Field idField = entityClass.getDeclaredField(metadata.idField);
            idField.setAccessible(true);
            if (idField.get(entity) == null) {
                idField.set(entity, nextId++);
            }
            return entity;
        } catch (Exception e) {
            throw new ORMException("ID generation failed", e);
        }
    }

    private void loadNextId() {
        if (!metadata.autoGenerateId)
            return;

        try {
            List<String> lines = Files.readAllLines(filePath);
            if (lines.size() > 1) {
                String lastLine = lines.get(lines.size() - 1);
                long lastId = Long.parseLong(lastLine.split(",")[0]);
                nextId = lastId + 1;
            }
        } catch (Exception e) {
            throw new ORMException("Failed to initialize ID sequence", e);
        }
    }

    private void appendToFile(String record) {
        try {
            Files.write(filePath, (record + System.lineSeparator()).getBytes(),
                    StandardOpenOption.APPEND);
        } catch (IOException e) {
            throw new ORMException("Failed to append record", e);
        }
    }

    private void writeAtomic(List<String> lines) {
        Path tempFile = null;
        try {
            tempFile = Files.createTempFile(filePath.getParent(), "temp", ".txt");
            Files.write(tempFile, lines, StandardCharsets.UTF_8);
            Files.move(tempFile, filePath, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            throw new ORMException("Atomic write failed", e);
        } finally {
            if (tempFile != null) {
                try {
                    Files.deleteIfExists(tempFile);
                } catch (IOException ignored) {
                }
            }
        }
    }

    /**
     * Custom ORM exception indicating operation failures
     */
    public static class ORMException extends RuntimeException {
        public ORMException(String message) {
            super(message);
        }

        public ORMException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    /**
     * Functional interface for conditional checks
     */
    @FunctionalInterface
    public interface Predicate<T> {
        boolean test(T t);
    }

    /**
     * Functional interface for transformations
     */
    @FunctionalInterface
    public interface Function<T, R> {
        R apply(T t);
    }
}