package com.group4.lib.data;

import java.io.*;
import java.lang.annotation.*;
import java.lang.reflect.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.locks.ReentrantLock;
import java.util.function.Function;
import java.util.function.Predicate;

/**
 * SimpleFileORM - A lightweight object-relational mapping system for text file
 * storage.
 * Provides basic CRUD operations with transaction support and type safety.
 *
 * @param <T> The entity type this ORM will manage
 */
public class SimpleFileORM<T> {
    private final Path filePath;
    private final ReentrantLock lock = new ReentrantLock();
    private final Class<T> entityClass;
    private final EntityMetadata metadata;
    private long nextId = 1;

    /**
     * Marks a class as a persistent entity
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.TYPE)
    public @interface Entity {
        /**
         * @return Optional custom name for the entity storage file
         */
        String name() default "";
    }

    /**
     * Marks a field as the entity's primary key
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface Id {
        /**
         * @return true if the ID should be auto-generated
         */
        boolean autoGenerated() default true;
    }

    /**
     * Marks a field for persistence in the text file
     */
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.FIELD)
    public @interface Column {
        /**
         * @return Optional custom column name
         */
        String name() default "";
    }

    private static class EntityMetadata {
        String idField;
        boolean autoGenerateId;
        // Store fields in a list to preserve order for serialization/deserialization
        List<Field> persistentFields = new ArrayList<>();
        // Use LinkedHashMap to preserve insertion order for columns based on field
        // declaration order
        Map<String, String> columnMappings = new LinkedHashMap<>();
        Map<String, Class<?>> fieldTypes = new HashMap<>();
        // Map from column name (as it appears in the file header) to the corresponding
        // Field object
        Map<String, Field> columnToFieldMap = new HashMap<>();
    }

    /**
     * Creates a new ORM instance for the specified entity class
     *
     * @param entityClass The entity class to manage
     * @param filePath    The storage file path
     * @throws ORMException If entity class is invalid or file initialization fails
     */
    public SimpleFileORM(Class<T> entityClass, String filePath) {
        this.entityClass = Objects.requireNonNull(entityClass, "Entity class cannot be null");
        this.filePath = Paths.get(filePath).toAbsolutePath();
        this.metadata = parseEntityMetadata();
        initializeStorage();
        loadNextId();
    }

    private EntityMetadata parseEntityMetadata() {
        validateEntityClass();
        EntityMetadata meta = new EntityMetadata();

        // Process entity-level annotation
        if (entityClass.isAnnotationPresent(Entity.class)) {
            Entity entityAnn = entityClass.getAnnotation(Entity.class);
            // Use annotation name if provided
            if (!entityAnn.name().isEmpty()) {
                // Could use this for file naming or schema validation
            }
        }

        // Process fields - iterate through declared fields to maintain a consistent
        // order
        for (Field field : entityClass.getDeclaredFields()) {
            field.setAccessible(true); // Set accessible once

            if (field.isAnnotationPresent(Id.class)) {
                meta.idField = field.getName();
                meta.autoGenerateId = field.getAnnotation(Id.class).autoGenerated();
                meta.fieldTypes.put(field.getName(), field.getType()); // Store ID field type
                meta.columnToFieldMap.put(meta.idField, field); // Map ID column name to field
            }
            if (field.isAnnotationPresent(Column.class)) {
                Column column = field.getAnnotation(Column.class);
                String columnName = column.name().isEmpty() ? field.getName() : column.name();
                meta.columnMappings.put(field.getName(), columnName); // Add to linked hash map
                meta.persistentFields.add(field); // Add to the ordered list of persistent fields
                meta.fieldTypes.put(field.getName(), field.getType()); // Store column field type
                meta.columnToFieldMap.put(columnName, field); // Map column name to field
            }
        }

        if (meta.idField == null) {
            throw new ORMException("Entity class must have a field annotated with @Id");
        }

        return meta;
    }

    private void validateEntityClass() {
        if (!entityClass.isAnnotationPresent(Entity.class)) {
            throw new ORMException("Entity class must be annotated with @Entity");
        }

        try {
            entityClass.getDeclaredConstructor();
        } catch (NoSuchMethodException e) {
            throw new ORMException("Entity class must have a public no-arg constructor", e);
        }
    }

    private void initializeStorage() {
        lock.lock();
        try {
            if (!Files.exists(filePath)) {
                Files.createDirectories(filePath.getParent());
                Files.createFile(filePath);
                writeHeader();
            }
        } catch (IOException e) {
            throw new ORMException("Storage initialization failed", e);
        } finally {
            lock.unlock();
        }
    }

    private void writeHeader() throws IOException {
        List<String> header = new ArrayList<>();
        if (metadata.autoGenerateId) {
            header.add(metadata.idField); // Use the actual ID field name in header
        }
        // Write header columns in the same order as the persistentFields list
        for (Field field : metadata.persistentFields) {
            header.add(metadata.columnMappings.get(field.getName()));
        }

        Files.write(filePath, Collections.singleton(String.join(",", header)),
                StandardCharsets.UTF_8);
    }

    /**
     * Persists a new entity to storage
     *
     * @param entity The entity to persist
     * @return The persisted entity with generated ID (if applicable)
     * @throws ORMException If persistence fails
     */
    public T create(T entity) {
        validateEntity(entity);
        lock.lock();
        try {
            if (metadata.autoGenerateId) {
                entity = generateId(entity);
            }
            String record = serializeEntity(entity);
            appendToFile(record);
            return entity;
        } finally {
            lock.unlock();
        }
    }

    /**
     * Retrieves all entities matching the predicate
     *
     * @param predicate The filter condition
     * @return List of matching entities (empty if none found)
     * @throws ORMException If query fails
     */
    public List<T> find(Predicate<T> predicate) {
        lock.lock();
        try {
            List<T> results = new ArrayList<>();
            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);
            if (lines.isEmpty())
                return results; // Handle empty file

            // Assuming the first line is the header
            List<String> headerFields = Arrays.asList(lines.get(0).split(",", -1)); // Use -1 to keep trailing empty
                                                                                    // strings
            // Basic header validation
            if (metadata.autoGenerateId && (headerFields.isEmpty() || !headerFields.get(0).equals(metadata.idField))) {
                throw new ORMException(
                        "File header is missing or has incorrect ID field at the beginning: " + metadata.idField);
            }
            if (!metadata.autoGenerateId && !headerFields.contains(metadata.idField)) {
                throw new ORMException("File header is missing the ID field: " + metadata.idField);
            }

            for (int i = 1; i < lines.size(); i++) { // Start from the second line (skip header)
                String line = lines.get(i);
                if (line.trim().isEmpty())
                    continue; // Skip empty lines

                T entity = deserializeEntity(line, headerFields);
                if (predicate.test(entity)) {
                    results.add(entity);
                }
            }
            return Collections.unmodifiableList(results);
        } catch (IOException e) {
            throw new ORMException("Query failed", e);
        } finally {
            lock.unlock();
        }
    }

    /**
     * Retrieves all entities from storage.
     *
     * @return List of all entities (empty if none found).
     * @throws ORMException If retrieval fails.
     */
    public List<T> findAll() {
        return find(entity -> true); // Find all entities by always returning true
    }

    /**
     * Updates entities matching the predicate
     *
     * @param predicate Filter condition
     * @param updater   Update function
     * @return Number of updated entities
     * @throws ORMException If update fails
     */
    public int update(Predicate<T> predicate, Function<T, T> updater) {
        lock.lock();
        try {
            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);
            if (lines.isEmpty())
                return 0; // Nothing to update

            List<String> newLines = new ArrayList<>();
            newLines.add(lines.get(0)); // Keep the header
            int updates = 0;

            List<String> headerFields = Arrays.asList(lines.get(0).split(",", -1));
            if (metadata.autoGenerateId && (headerFields.isEmpty() || !headerFields.get(0).equals(metadata.idField))) {
                throw new ORMException(
                        "File header is missing or has incorrect ID field at the beginning: " + metadata.idField);
            }
            if (!metadata.autoGenerateId && !headerFields.contains(metadata.idField)) {
                throw new ORMException("File header is missing the ID field: " + metadata.idField);
            }

            for (int i = 1; i < lines.size(); i++) { // Start from the second line
                String line = lines.get(i);
                if (line.trim().isEmpty()) {
                    newLines.add(line); // Keep empty lines
                    continue;
                }

                T entity = deserializeEntity(line, headerFields);
                if (predicate.test(entity)) {
                    T updated = updater.apply(entity);
                    if (updated != null) { // If updater returns null, it means delete
                        validateEntity(updated);
                        newLines.add(serializeEntity(updated));
                        updates++;
                    } else {
                        // Entity is deleted, do not add to newLines
                        updates++; // Count as a deletion
                    }
                } else {
                    newLines.add(line); // Keep lines that don't match the predicate
                }
            }

            if (updates > 0 || newLines.size() != lines.size()) { // Write if changes were made or lines were removed
                writeAtomic(newLines);
            }
            return updates;
        } catch (IOException e) {
            throw new ORMException("Update failed", e);
        } finally {
            lock.unlock();
        }
    }

    /**
     * Deletes entities matching the predicate
     *
     * @param predicate Filter condition
     * @return Number of deleted entities
     * @throws ORMException If deletion fails
     */
    public int delete(Predicate<T> predicate) {
        lock.lock();
        try {
            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);
            if (lines.isEmpty())
                return 0; // Nothing to delete

            List<String> newLines = new ArrayList<>();
            newLines.add(lines.get(0)); // Keep the header
            int deletions = 0;

            List<String> headerFields = Arrays.asList(lines.get(0).split(",", -1));
            if (metadata.autoGenerateId && (headerFields.isEmpty() || !headerFields.get(0).equals(metadata.idField))) {
                throw new ORMException(
                        "File header is missing or has incorrect ID field at the beginning: " + metadata.idField);
            }
            if (!metadata.autoGenerateId && !headerFields.contains(metadata.idField)) {
                throw new ORMException("File header is missing the ID field: " + metadata.idField);
            }

            for (int i = 1; i < lines.size(); i++) { // Start from the second line
                String line = lines.get(i);
                if (line.trim().isEmpty()) {
                    newLines.add(line); // Keep empty lines
                    continue;
                }

                T entity = deserializeEntity(line, headerFields);
                if (predicate.test(entity)) {
                    // Entity matches predicate, do not add to newLines (delete it)
                    deletions++;
                } else {
                    newLines.add(line); // Keep lines that don't match the predicate
                }
            }

            if (deletions > 0) { // Only write if deletions occurred
                writeAtomic(newLines);
            }
            return deletions;
        } catch (IOException e) {
            throw new ORMException("Delete failed", e);
        } finally {
            lock.unlock();
        }
    }

    // Serialization methods
    private String serializeEntity(T entity) {
        List<String> values = new ArrayList<>();
        try {
            // Ensure the ID field is serialized first if auto-generated
            if (metadata.autoGenerateId) {
                Field idField = entityClass.getDeclaredField(metadata.idField);
                // idField.setAccessible(true); // Already set accessible in parseEntityMetadata
                Object idValue = idField.get(entity);
                if (idValue == null) {
                    throw new ORMException("Entity with auto-generated ID has a null ID field during serialization.");
                }
                values.add(idValue.toString());
            }

            // Serialize fields in the consistent order defined in persistentFields
            for (Field field : metadata.persistentFields) {
                // field.setAccessible(true); // Already set accessible in parseEntityMetadata
                Object value = field.get(entity);
                // Handle null values by writing an empty string
                values.add(value == null ? "" : value.toString());
            }
        } catch (Exception e) {
            throw new ORMException("Serialization failed for entity: " + entity, e);
        }
        return String.join(",", values);
    }

    // Modified deserializeEntity to take header fields for column mapping
    private T deserializeEntity(String line, List<String> headerFields) {
        try {
            T entity = entityClass.getDeclaredConstructor().newInstance();
            String[] parts = line.split(",", -1); // Use -1 to keep trailing empty strings

            // --- Refined mapping from header column to entity field ---
            for (int i = 0; i < headerFields.size(); i++) {
                String headerColumnName = headerFields.get(i).trim(); // Trim whitespace from header name
                String value = (i < parts.length) ? parts[i] : ""; // Handle missing columns

                // Find the corresponding Field object using the columnToFieldMap
                Field entityField = metadata.columnToFieldMap.get(headerColumnName);

                if (entityField != null) {
                    // entityField.setAccessible(true); // Already set accessible in
                    // parseEntityMetadata
                    Class<?> fieldType = entityField.getType();

                    // Parse the value based on the field type
                    Object parsedValue = parseValue(value, fieldType);
                    entityField.set(entity, parsedValue);
                } else {
                    // This might happen if the file has columns not mapped in the entity
                    System.err.println("Warning: Column '" + headerColumnName
                            + "' found in file header but not mapped to an entity field in " + entityClass.getName());
                }
            }
            // --- End of refined mapping ---

            return entity;
        } catch (NoSuchMethodException e) {
            throw new ORMException("Missing no-arg constructor in " + entityClass.getName(), e);
        } catch (InstantiationException | IllegalAccessException | InvocationTargetException e) {
            throw new ORMException("Failed to instantiate entity", e);
        } catch (Exception e) {
            throw new ORMException("Deserialization failed for line: '" + line + "'", e);
        }
    }

    // Modified parseValue to handle Enum types
    private Object parseValue(String value, Class<?> type) {
        // Handle null or empty string for non-primitive types (treat as null)
        if (value == null || value.trim().isEmpty()) { // Also trim value before checking for empty
            if (type.isPrimitive()) {
                // Return default value for primitive types if input is null or empty
                if (type == int.class)
                    return 0;
                if (type == long.class)
                    return 0L;
                if (type == double.class)
                    return 0.0;
                if (type == boolean.class)
                    return false;
                // Add other primitive types if needed (byte, short, float, char)
                throw new ORMException("Unsupported primitive type: " + type.getName() + " for empty value.");
            }
            return null; // Return null for non-primitive types
        }

        try {
            // Use value.trim() before parsing to handle potential whitespace
            String trimmedValue = value.trim();

            if (type == String.class)
                return trimmedValue;
            if (type == Integer.class || type == int.class)
                return Integer.parseInt(trimmedValue);
            if (type == Long.class || type == long.class)
                return Long.parseLong(trimmedValue);
            if (type == Double.class || type == double.class)
                return Double.parseDouble(trimmedValue);
            if (type == Boolean.class || type == boolean.class)
                return Boolean.parseBoolean(trimmedValue);

            // --- Add support for Enum types ---
            if (type.isEnum()) {
                // Assuming the value string matches the enum constant name
                // Use value.trim() in case of leading/trailing whitespace
                return Enum.valueOf((Class<Enum>) type, trimmedValue);
            }
            // ----------------------------------

            throw new ORMException("Unsupported type for deserialization: " + type.getName());
        } catch (NumberFormatException e) {
            throw new ORMException("Invalid number format for value '" + value + "' and type " + type.getName(), e);
        } catch (IllegalArgumentException e) {
            // Catch IllegalArgumentException for Enum.valueOf if the string doesn't match
            // an enum constant
            if (type.isEnum()) {
                throw new ORMException("Invalid enum constant '" + value + "' for enum type " + type.getName(), e);
            }
            throw new ORMException("Invalid argument for value '" + value + "' and type " + type.getName(), e);
        } catch (Exception e) {
            throw new ORMException("Error parsing value '" + value + "' for type " + type.getName(), e);
        }
    }

    // Helper methods
    private void validateEntity(T entity) {
        if (entity == null) {
            throw new ORMException("Cannot validate a null entity.");
        }
        try {
            // Validate ID field if it's not auto-generated
            if (!metadata.autoGenerateId) {
                Field idField = entityClass.getDeclaredField(metadata.idField);
                // idField.setAccessible(true); // Already set accessible in parseEntityMetadata
                if (idField.get(entity) == null) {
                    throw new ORMException(
                            "ID field '" + metadata.idField + "' cannot be null for entity " + entityClass.getName());
                }
            }

            // Validate persistent fields
            for (Field field : metadata.persistentFields) {
                // field.setAccessible(true); // Already set accessible in parseEntityMetadata
                Object value = field.get(entity);

                // Basic validation: non-primitive fields with @Column should not be null
                // unless explicitly allowed (which this simple ORM doesn't support yet)
                if (value == null && field.getAnnotation(Column.class) != null && !field.getType().isPrimitive()) {
                    // Note: Primitive types (int, boolean etc.) cannot be null,
                    // they will have default values (0, false).
                    throw new ORMException("Non-nullable field '" + field.getName() + "' cannot be null in entity "
                            + entityClass.getName());
                }
                // Add more specific validation based on field type or custom annotations if
                // needed
            }
        } catch (Exception e) {
            throw new ORMException("Entity validation failed for entity: " + entity, e);
        }
    }

    private T generateId(T entity) {
        try {
            Field idField = entityClass.getDeclaredField(metadata.idField);
            // idField.setAccessible(true); // Already set accessible in parseEntityMetadata
            // Only generate ID if it's currently null
            if (idField.get(entity) == null) {
                // Ensure the ID field is a supported type (Long, Integer, etc.)
                Class<?> idType = idField.getType();
                if (idType == Long.class || idType == long.class) {
                    idField.set(entity, nextId++);
                } else if (idType == Integer.class || idType == int.class) {
                    if (nextId > Integer.MAX_VALUE) {
                        throw new ORMException("Auto-generated ID exceeds maximum value for Integer type.");
                    }
                    idField.set(entity, (int) nextId++);
                } else {
                    throw new ORMException("Unsupported ID type for auto-generation: " + idType.getName());
                }
            }
            return entity;
        } catch (Exception e) {
            throw new ORMException("ID generation failed for entity: " + entity, e);
        }
    }

    private void loadNextId() {
        if (!metadata.autoGenerateId)
            return;

        lock.lock(); // Lock while reading file to determine next ID
        try {
            if (!Files.exists(filePath)) {
                nextId = 1; // Start from 1 if file doesn't exist
                return;
            }

            List<String> lines = Files.readAllLines(filePath, StandardCharsets.UTF_8);
            if (lines.isEmpty() || lines.size() <= 1) { // Only header or empty file (after header)
                nextId = 1;
                return;
            }

            // Find the index of the ID column in the header
            List<String> headerFields = Arrays.asList(lines.get(0).split(",", -1));
            int idColumnIndex = headerFields.indexOf(metadata.idField);
            if (idColumnIndex == -1) {
                throw new ORMException("File header is missing the ID field: " + metadata.idField);
            }

            long maxId = 0;
            for (int i = 1; i < lines.size(); i++) { // Start from the second line
                String line = lines.get(i);
                if (line.trim().isEmpty())
                    continue; // Skip empty lines

                String[] parts = line.split(",", -1);
                if (parts.length > idColumnIndex) {
                    try {
                        long currentId = Long.parseLong(parts[idColumnIndex].trim()); // Trim ID value before parsing
                        if (currentId > maxId) {
                            maxId = currentId;
                        }
                    } catch (NumberFormatException e) {
                        System.err.println(
                                "Warning: Could not parse ID in line: " + line + ". Skipping for next ID calculation.");
                        // Continue processing other lines
                    }
                } else {
                    System.err.println("Warning: Line does not have enough columns to contain ID field at index "
                            + idColumnIndex + ": " + line);
                }
            }
            nextId = maxId + 1;
            System.out.println("Initialized next auto-generated ID to: " + nextId);

        } catch (IOException e) {
            throw new ORMException("Failed to initialize ID sequence from file", e);
        } catch (Exception e) {
            throw new ORMException("An unexpected error occurred while initializing ID sequence", e);
        } finally {
            lock.unlock();
        }
    }

    private void appendToFile(String record) {
        lock.lock(); // Lock while appending
        try {
            // Ensure the directory exists before writing
            Files.createDirectories(filePath.getParent());
            Files.write(filePath, (record + System.lineSeparator()).getBytes(StandardCharsets.UTF_8),
                    StandardOpenOption.APPEND, StandardOpenOption.CREATE); // Use CREATE in case file was deleted
        } catch (IOException e) {
            throw new ORMException("Failed to append record to file: " + filePath, e);
        } finally {
            lock.unlock();
        }
    }

    private void writeAtomic(List<String> lines) {
        lock.lock(); // Lock while writing atomically
        Path tempFile = null;
        try {
            Files.createDirectories(filePath.getParent()); // Ensure directory exists
            tempFile = Files.createTempFile(filePath.getParent(), "temp", ".txt");
            Files.write(tempFile, lines, StandardCharsets.UTF_8);
            Files.move(tempFile, filePath, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE); // Use
                                                                                                                 // ATOMIC_MOVE
        } catch (IOException e) {
            throw new ORMException("Atomic write failed for file: " + filePath, e);
        } finally {
            if (tempFile != null) {
                try {
                    // Clean up temp file, ignore errors as it might have been moved
                    Files.deleteIfExists(tempFile);
                } catch (IOException ignored) {
                }
            }
            lock.unlock();
        }
    }

    /**
     * Custom ORM exception indicating operation failures
     */
    public static class ORMException extends RuntimeException {
        public ORMException(String message) {
            super(message);
        }

        public ORMException(String message, Throwable cause) {
            super(message, cause);
        }
    }

    // Functional interfaces (already defined)
    // @FunctionalInterface
    // public interface Predicate<T> {
    // boolean test(T t);
    // }

    // @FunctionalInterface
    // public interface Function<T, R> {
    // R apply(T t);
    // }
}
